### ISSUE TITLE
Problems with log-in since few days

### ISSUE THREAD

**Issue by Tomiliy** [iobroker-community-adapters/ioBroker.botvac#16]
Since few days, my adapter log shows:

botvac.0 | 2020-09-27 17:50:33.728 | warn | (757) login failed

did anyone knows what toDo? He sends this status every 15 minutes.. And the Bot is not working via script
Logindata is correct, Neato is functioning via mobileapp perfectly.
Please help.

Thanks

**Comment by Tomiliy** [comment]
fixed. 
work like a charme, like before

**Comment by Tomiliy** [comment]
i don't know what happend, i don't changed anything

**Comment by Tomiliy** [comment]
Problem is back.
Adapter cannot log into Neato account.
Please help
What is to do? What Logfile you need?

**Comment by Tomiliy** [comment]
Please help
What is to do? What Logfile you need?

can anyone help?

**Comment by Tomiliy** [comment]
reinstalling the adapter doesen't resolve the problem..
Please help:

`host.buanet-iobroker1 | 2020-10-01 21:46:41.207 | info | Update repository "default" under "http://download.iobroker.net/sources-dist.json"
-- | -- | -- | --
botvac.0 | 2020-10-01 21:45:30.751 | warn | (16540) login failed
botvac.0 | 2020-10-01 21:45:30.610 | info | (16540) starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.botvac, node: v12.18.4, js-controller: 3.1.6
host.buanet-iobroker1 | 2020-10-01 21:45:27.804 | info | instance system.adapter.botvac.0 started with pid 16540
host.buanet-iobroker1 | 2020-10-01 21:45:25.323 | info | instance system.adapter.botvac.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
botvac.0 | 2020-10-01 21:45:24.766 | info | (16381) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
botvac.0 | 2020-10-01 21:45:24.764 | info | (16381) terminating
botvac.0 | 2020-10-01 21:45:24.761 | info | (16381) Got terminate signal TERMINATE_YOURSELF
host.buanet-iobroker1 | 2020-10-01 21:45:24.752 | info | stopInstance system.adapter.botvac.0 send kill signal
host.buanet-iobroker1 | 2020-10-01 21:45:24.741 | info | stopInstance system.adapter.botvac.0 (force=false, process=true)
botvac.0 | 2020-10-01 21:45:04.220 | warn | (16381) login failed
botvac.0 | 2020-10-01 21:45:03.998 | info | (16381) starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.botvac, node: v12.18.4, js-controller: 3.1.6
host.buanet-iobroker1 | 2020-10-01 21:45:00.525 | info | instance system.adapter.botvac.0 started with pid 16381
host.buanet-iobroker1 | 2020-10-01 21:44:58.514 | info | iobroker exit 0
`

**Comment by Maveric2005** [comment]
Same Problem here. 


botvac.0 | 2021-04-24 15:29:17.470 | warn | (950) login failed
-- | -- | -- | --
botvac.0 | 2021-04-24 15:24:16.738 | warn | (950) login failed
botvac.0 | 2021-04-24 15:19:15.667 | warn | (950) login failed

**Comment by mcm1957** [comment]
maybe related to #46

If the problem still exists with current release (2.0.1) please open a new issue and attach logs.
