### ISSUE TITLE
RESTART LOOP DETECTED

### ISSUE THREAD

**Issue by Hini2001** [iobroker-community-adapters/ioBroker.botvac#24]
Hello,

i am actually facing the Same Problem like in Issue number #14  .

I hope you can help me.
System is a RASPI 4 with ioBroker. 
Node.js v12.22.1 
NPM 6.14.12
JS-Controller 3.2.16

host | 2021-10-09 14:38:01.061 | warn | Do not restart adapter system.adapter.botvac.0 because restart loop detected
-- | -- | -- | --
host | 2021-10-09 14:38:01.060 | info | Restart adapter system.adapter.botvac.0 because enabled
host | 2021-10-09 14:38:01.060 | error | instance system.adapter.botvac.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
botvac.0 | 2021-10-09 14:38:00.436 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
botvac.0 | 2021-10-09 14:38:00.435 | info | terminating
botvac.0 | 2021-10-09 14:38:00.416 | error | Cannot read property 'isCharging' of undefined
botvac.0 | 2021-10-09 14:38:00.415 | error | TypeError: Cannot read property 'isCharging' of undefined at Robot.<anonymous> (/opt/iobroker/node_modules/node-botvac/lib/robot.js:40:50) at /opt/iobroker/node_modules/node-botvac/lib/robot.js:320:17 at Request._callback (/opt/iobroker/node_modules/node-botvac/lib/api.js:42:45) at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22) at Request.emit (events.js:314:20) at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10) at Request.emit (events.js:314:20) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1076:12) at Object.onceWrapper (events.js:420:28) at IncomingMessage.emit (events.js:326:22)
botvac.0 | 2021-10-09 14:38:00.413 | error | uncaught exception: Cannot read property 'isCharging' of undefined
botvac.0 | 2021-10-09 14:37:59.616 | info | devices found: 1
botvac.0 | 2021-10-09 14:37:58.459 | info | starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.botvac, node: v12.22.1, js-controller: 3.2.16
host | 2021-10-09 14:37:56.162 | info | instance system.adapter.botvac.0 started with pid 31108

I hope you can help me.

Greetings

**Comment by Hini2001** [comment]
Nobody an idea? :-(

**Comment by Slider-Override** [comment]
I have the same since last week, no changes on my end, reinstall did not fix the issue :-(

**Comment by mcm1957** [comment]
maybe related to #46

If the problem still exists with current release (2.0.1) please open a new issue and attach logs.
