### ISSUE TITLE
Cannot read property 'isCharging' of undefined

### ISSUE THREAD

**Issue by Slider-Override** [iobroker-community-adapters/ioBroker.botvac#25]
Restart loop detected:

Since last week i get this error, the Adapther did not start anymore, and idea ?

<html><body>

botvac.0 | 2021-12-25 15:01:15.246 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
botvac.0 | 2021-12-25 15:01:15.246 | info | terminating
botvac.0 | 2021-12-25 15:01:15.243 | error | Cannot read property 'isCharging' of undefined
botvac.0 | 2021-12-25 15:01:15.243 | error | TypeError:  Cannot read property 'isCharging' of undefined    at  Robot.<anonymous>  (/opt/iobroker/node_modules/node-botvac/lib/robot.js:40:50)    at  /opt/iobroker/node_modules/node-botvac/lib/robot.js:320:17    at  Request._callback  (/opt/iobroker/node_modules/node-botvac/lib/api.js:42:45)    at  Request.self.callback  (/opt/iobroker/node_modules/request/request.js:185:22)    at  Request.emit (events.js:314:20)    at Request.<anonymous>  (/opt/iobroker/node_modules/request/request.js:1154:10)    at  Request.emit (events.js:314:20)    at IncomingMessage.<anonymous>  (/opt/iobroker/node_modules/request/request.js:1076:12)    at  Object.onceWrapper (events.js:420:28)    at IncomingMessage.emit  (events.js:326:22)
botvac.0 | 2021-12-25 15:01:15.242 | error | uncaught exception: Cannot read property 'isCharging' of undefined

</body>
</html>

**Comment by mcm1957** [comment]
maybe related to #46

If the problem still exists with current release (2.0.1) please open a new issue and attach logs.
