### ISSUE TITLE
BUG: Warning State value to set for "botvac.0.Erdgeschoss.commands.spotWidth" has value "0" less than min "100"

### ISSUE THREAD

**Issue by Mephisto090** [iobroker-community-adapters/ioBroker.botvac#29]
Hello,

the picture really says it all. I can't change the value either.

![image](https://user-images.githubusercontent.com/85995176/204782228-c64ee0c9-951a-4f9a-93dd-b84c34ad5b2c.png)

**Comment by Pedder007** [comment]
Yep, das gleiche hier, hatte die 1.0.4  via Link installiert.
Die Zeitabstände entsprechen dem in der Instanz eingestelltem Polling-Intervall in Sekunden.

**Comment by mcm1957** [comment]
Danke für die INfo.
Dieser Fehler wurde noch nicht nagegangen / behoben.

2.0.0 wurde kurzfristig veröffentlicht da ältere Versionen mit js-controller 5 nicht kompatibel ist

**Comment by Hini2001** [comment]
Das gleiche hier. Gibt's schon ne Lösung?
Liebe Grüße und vielen Dank für die ganze Arbeit.

**Comment by mcm1957** [comment]
Leider meines Wissens nach nein.
Ich habs mal auf meine Todo Liste gesetzt - aber keien Ahnung wann ich dazu komm.
Falls jemand einen PR erstellen kann / will - ist gern gesehen.

**Comment by mcm1957** [comment]
fixed at 2.0.2

**Comment by mcm1957** [comment]
ATTENTION:
To correct the state definitions its required to delet the effected states manually. They will be recreated at next adapgetr start with correct configuration.
