### ISSUE TITLE
js-controller 5 not supported

### ISSUE THREAD

**Issue by thogens** [iobroker-community-adapters/ioBroker.botvac#31]
After installing Node.js v18.16.1, the adapter doesn't start anymore.
Error message below:

host.iobroker | 2023-07-18 17:53:43.453 | info | Rebuild for adapter system.adapter.botvac.0 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually.
-- | -- | -- | --
host.iobroker | 2023-07-18 17:53:43.453 | error | instance system.adapter.botvac.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker | 2023-07-18 17:53:43.453 | error | Caught by controller[0]: Node.js v18.16.1
host.iobroker | 2023-07-18 17:53:43.453 | error | Caught by controller[0]: }
host.iobroker | 2023-07-18 17:53:43.453 | error | Caught by controller[0]: ]
host.iobroker | 2023-07-18 17:53:43.453 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.botvac/main.js'
host.iobroker | 2023-07-18 17:53:43.453 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.botvac/lib/utils.js',
host.iobroker | 2023-07-18 17:53:43.453 | error | Caught by controller[0]: requireStack: [
host.iobroker | 2023-07-18 17:53:43.452 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.iobroker | 2023-07-18 17:53:43.452 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1143:19) {
host.iobroker | 2023-07-18 17:53:43.452 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:960:12)
host.iobroker | 2023-07-18 17:53:43.452 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1119:32)
host.iobroker | 2023-07-18 17:53:43.452 | error | Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
host.iobroker | 2023-07-18 17:53:43.452 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1256:14)
host.iobroker | 2023-07-18 17:53:43.452 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.botvac/lib/utils.js:46:25)
host.iobroker | 2023-07-18 17:53:43.452 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:110:18)
host.iobroker | 2023-07-18 17:53:43.452 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1143:19)
host.iobroker | 2023-07-18 17:53:43.452 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:922:27)
host.iobroker | 2023-07-18 17:53:43.452 | error | Caught by controller[0]: at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
host.iobroker | 2023-07-18 17:53:43.451 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.botvac/main.js
host.iobroker | 2023-07-18 17:53:43.451 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.botvac/lib/utils.js
host.iobroker | 2023-07-18 17:53:43.451 | error | Caught by controller[0]: Require stack:
host.iobroker | 2023-07-18 17:53:43.451 | error | Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js'
host.iobroker | 2023-07-18 17:53:43.451 | error | Caught by controller[0]: ^
host.iobroker | 2023-07-18 17:53:43.451 | error | Caught by controller[0]: throw err;
host.iobroker | 2023-07-18 17:53:43.450 | error | Caught by controller[0]: node:internal/modules/cjs/loader:1080

**Comment by mcm1957** [comment]
looks more like js-controller 5 issue.
To be checked

**Comment by JohGrei** [comment]
same issue on my side after installing js-controller 5.0.12

**Comment by mcm1957** [comment]
fixed with 2.0.0
