### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [iobroker-community-adapters/ioBroker.botvac#7]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/Pmant/ioBroker.botvac

- [ ] [E104] No common.titleLang found in io-package.json
- [ ] [E114] No adapter are allowed in the repo without admin3 support
- [ ] [E115] No license found in io-package.json
- [ ] [E130] No news found in io-package.json
- [ ] [E150] No common.connectionType found in io-package.json
- [ ] [E152] No common.dataSource found in io-package.json
- [ ] [E201] Bluefox was not found in the collaborators on NPM!. Please execute in adapter directory: "npm owner add bluefox iobroker.botvac"
- [ ] [E300] Not found on travis. Please setup travis
- [ ] [E801] No repository about text found. Please go to "https://github.com/Pmant/ioBroker.botvac", press the settings button beside the about title and add the description.
- [ ] [E802] No topics found in the repository. Please go to "https://github.com/Pmant/ioBroker.botvac", press the settings button beside the about title and add some topics.
- [ ] [E605] No actual year found in copyright. Please add "Copyright (c) 2022 Pmant <patrickmo@gmx.de>" at the end of README.md
- [ ] [E701] No actual year found in LICENSE. Please add "Copyright (c) 2022 Pmant <patrickmo@gmx.de>" at the start of LICENSE

I have also found warnings that may be fixed if possible.

- [ ] [W113] Adapter should support compact mode

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by ioBrokerChecker** [comment]
Do you need help fixing the bugs?

**Comment by mcm1957** [comment]
outdated
