### ISSUE TITLE
Installation issues of the adapter

### ISSUE THREAD

**Issue by padddy79** [iobroker-community-adapters/ioBroker.botvac#74]
Hello,

I have an issues with installation of the adapter with npm version. 
Following error meassage was displayed at iobroker:

ERROR: Process exited with code 25
$ iobroker url https://github.com/iobroker-community-adapters/ioBroker.botvac#200-alpha1-2023-09-15 --host BRIX03 --debug
install iobroker-community-adapters/ioBroker.botvac#34f4a07e0ed92c9895c57c686a15ecf2596baa4a
NPM version: 9.8.1
Installing iobroker-community-adapters/ioBroker.botvac#34f4a07e0ed92c9895c57c686a15ecf2596baa4a... (System call)
npm ERR! code ENOENT
npm ERR! syscall spawn git npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred npm ERR! enoent This is related to npm not being able to find a file. npm ERR! enoent
npm ERR! A complete log of this run can be found in: C:\Windows\system32\config\systemprofile\AppData\Local\npm-cache\_logs\2023-11-04T14_11_16_935Z-debug-0.log
npm ERR! code ENOENTnpm ERR! syscall spawn gitnpm ERR! path gitnpm ERR! errno -4058npm ERR! enoent An unknown git error occurrednpm ERR! enoent This is related to npm not being able to find a file.npm ERR! enoent npm ERR! A complete log of this run can be found in: C:\Windows\system32\config\systemprofile\AppData\Local\npm-cache\_logs\2023-11-04T14_11_16_935Z-debug-0.log
host.BRIX03 Cannot install iobroker-community-adapters/ioBroker.botvac#34f4a07e0ed92c9895c57c686a15ecf2596baa4a: 4294963238

ERROR: Process exited with code 25

What can be the problem? With old version on another systems it works.
THX!

**Comment by mcm1957** [comment]
Please use normal installation via admin page.

**If this does not succeed please ask at forum (forum.iobroker.net),**
Please attach the output of iob diag to your posting (as this will be the first question) and the version of the adapter you try to install.
